### ISSUE TITLE
Consistancy with Web

### ISSUE THREAD

**Issue by ThibaultAr** [googlevr/poly-toolkit-unity#6] opened 2018-03-12 16:48 UTC
Hi,
I use both Unity Toolkit and Web Toolkit in Three.js to edit model in web view and then load them in unity using the asset ID. 
The problem is that when I load some models (especially those by "Poly by Google") the quaternion/rotation/orientation is not the same as the one on the web.
We triied to correct the rotation because we saw that coordinate systems were not the same in Three and Unity.

Is this a known issue ? Is there a solution to counter this in unity or Web ? 
Is there extra orientation transformations made on model while importing in unity ? 

Thanks

**Comment by btco** [comment] 2018-03-26 17:24
Hey!

Some of the inconsistencies are intentional and are because Unity and Three.js use different coordinate systems by design, and we want assets to be consistent with the target platform for ease of use. Unity uses a left-handed system where Y is up, Z is forward and X is right (similar to DirectX), while Three.js, WebGL, OpenGL use the traditional right-handed system where Z is *back*.

Can you give more details about what you are trying to achieve and why it's important to have consistent coordinate systems in Unity and Three.js? Is your project targeting both platforms?

**Comment by btco** [comment] 2018-05-24 18:15
Closing this for now, since we don't have a repro case. Please reopen if you find a repro case that we can use to debug this!

**Closed by btco** 2018-05-24 18:15 UTC
