### ISSUE TITLE
Poly toolkit changes behaviour of ARCore

### ISSUE THREAD

**Issue by oreyg** [googlevr/poly-toolkit-unity#14] opened 2018-06-01 14:42 UTC
Without PolyToolkitManager on the scene
https://drive.google.com/file/d/1E4nZEEEz_Du85E71c2j9GWrJrD3gMVUh/view?usp=sharing

With PolyToolkitManager
https://drive.google.com/file/d/1FyHsuKLNneaCATksrYW1NYy1ZkWPz7D8/view?usp=sharing

Without PolyToolkitManager on the scene ARCore succesfully restores its state after loosing and regaining camera feed. In these videos, I use the default class that comes with ARCore examples to generate and display planes (Only difference is in the shader).  

To reproduce: 
1. Download official ARCore-Unity-Sdk
https://github.com/google-ar/arcore-unity-sdk
2. Import Poly toolkit.
3. Open CloudAnchor scene.
4. Add PolyToolkitManager to the scene.

**Comment by btco** [comment] 2018-06-04 13:04
We're working on that. In fact, the memory allocation bug was already fixed at the tip of tree, but isn't yet part of a release. So if you just copy over the version of WebRequestManager.cs from the latest commit in this repo, it should work.

**Comment by btco** [comment] 2018-06-04 13:06
Closing as duplicate of #4
This fix will be part of the next release. For now, please patch your copy from the tip of tree.

**Closed by btco** 2018-06-04 13:06 UTC
