### ISSUE TITLE
Poly on Unity 2018 doesn't import textures properly

### ISSUE THREAD

**Issue by mitchellcairns** [googlevr/poly-toolkit-unity#8] opened 2018-03-28 22:25 UTC
I adapted the Poly Toolkit to work with 2018... only having a few issues

First; the toolkit doesn't remember my google sign-in after I quit and re-open the project
Second: textures are all red (one color) when importing. 

I know that poly toolkit isn't officially supported on Unity 2018, but I figured I'd report that everything except these two things seem to work without much modification.

**Comment by btco** [comment] 2018-03-30 20:33
Hi! Yes, we have a few things to fix for 2018, we'll fix in the next release. Thanks for letting us know!

**Comment by btco** [comment] 2018-05-21 21:16
@mitchellcairns Have you tested importing using the latest version of 2018? I can't repro the texture problem on 2018.1.0.f2. If you can still repro, can you provide a link to an asset where you observed it?

Thanks!

**Comment by btco** [comment] 2018-05-22 15:31
I fixed the sign-in issue (hopefully).
Since we can't repro the texture issue, I will close this for now. If you can still repro the texture problem, please reopen and mention an asset that reproduces the problem.

Thank you for reporting!

**Closed by btco** 2018-05-22 15:31 UTC
